#pragma once
namespace RBX {

	namespace Text
	{
		enum Font   {
			FONT_LEGACY, 
			FONT_ARIAL, 
			FONT_ARIALBOLD, 
			FONT_SOURCESANS, 
			FONT_SOURCESANSBOLD, 
			FONT_SOURCESANSLIGHT,
			FONT_SOURCESANSITALIC,  
			FONT_BODONI,
			FONT_GARAMOND,
			FONT_CARTOON,
			FONT_CODE,
			FONT_HIGHWAY,
			FONT_SCIFI,
			FONT_ARCADE,
			FONT_FANTASY,
			FONT_ANTIQUE,
			FONT_SOURCESANSSEMIBOLD,
			FONT_GOTHAM,
			FONT_GOTHAMSEMIBOLD,
			FONT_GOTHAMBOLD,
			FONT_GOTHAMBLACK,
			FONT_LAST
		};
		// Font drawing params - copied from G3D
		enum XAlign {XALIGN_RIGHT, XALIGN_LEFT, XALIGN_CENTER};

		enum YAlign {YALIGN_TOP, /*YALIGN_BASELINE,*/ YALIGN_CENTER, YALIGN_BOTTOM};


	}
}