CFLAGS=-I"hlsl2glslfork/hlslang/MachineIndependent" -I"hlsl2glslfork/hlslang/OSDependent/Mac" -I"glsl-optimizer/include" -I"glsl-optimizer/src" -I"glsl-optimizer/src/mesa" -I"glsl-optimizer/src/glsl" -I"glsl-optimizer/src/mapi" -I"../../ClientShared" -DNDEBUG -DMOJOSHADER_NO_VERSION_INCLUDE -O2 -c

SOURCES=
SOURCES+=glsl-optimizer/src/glsl/ast_array_index.cpp
SOURCES+=glsl-optimizer/src/glsl/ast_expr.cpp
SOURCES+=glsl-optimizer/src/glsl/ast_function.cpp
SOURCES+=glsl-optimizer/src/glsl/ast_to_hir.cpp
SOURCES+=glsl-optimizer/src/glsl/ast_type.cpp
SOURCES+=glsl-optimizer/src/glsl/builtin_functions.cpp
SOURCES+=glsl-optimizer/src/glsl/builtin_types.cpp
SOURCES+=glsl-optimizer/src/glsl/builtin_variables.cpp
SOURCES+=glsl-optimizer/src/glsl/glcpp/glcpp-lex.c
SOURCES+=glsl-optimizer/src/glsl/glcpp/glcpp-parse.c
SOURCES+=glsl-optimizer/src/glsl/glcpp/pp.c
SOURCES+=glsl-optimizer/src/glsl/glsl_lexer.cpp
SOURCES+=glsl-optimizer/src/glsl/glsl_optimizer.cpp
SOURCES+=glsl-optimizer/src/glsl/glsl_parser.cpp
SOURCES+=glsl-optimizer/src/glsl/glsl_parser_extras.cpp
SOURCES+=glsl-optimizer/src/glsl/glsl_symbol_table.cpp
SOURCES+=glsl-optimizer/src/glsl/glsl_types.cpp
SOURCES+=glsl-optimizer/src/glsl/hir_field_selection.cpp
SOURCES+=glsl-optimizer/src/glsl/ir.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_basic_block.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_builder.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_clone.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_constant_expression.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_equals.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_expression_flattening.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_function.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_function_can_inline.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_function_detect_recursion.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_hierarchical_visitor.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_hv_accept.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_import_prototypes.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_print_glsl_visitor.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_print_metal_visitor.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_print_visitor.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_rvalue_visitor.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_stats.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_unused_structs.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_validate.cpp
SOURCES+=glsl-optimizer/src/glsl/ir_variable_refcount.cpp
SOURCES+=glsl-optimizer/src/glsl/link_atomics.cpp
SOURCES+=glsl-optimizer/src/glsl/link_functions.cpp
SOURCES+=glsl-optimizer/src/glsl/link_interface_blocks.cpp
SOURCES+=glsl-optimizer/src/glsl/link_uniform_block_active_visitor.cpp
SOURCES+=glsl-optimizer/src/glsl/link_uniform_blocks.cpp
SOURCES+=glsl-optimizer/src/glsl/link_uniform_initializers.cpp
SOURCES+=glsl-optimizer/src/glsl/link_uniforms.cpp
SOURCES+=glsl-optimizer/src/glsl/link_varyings.cpp
SOURCES+=glsl-optimizer/src/glsl/linker.cpp
SOURCES+=glsl-optimizer/src/glsl/loop_analysis.cpp
SOURCES+=glsl-optimizer/src/glsl/loop_controls.cpp
SOURCES+=glsl-optimizer/src/glsl/loop_unroll.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_clip_distance.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_discard.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_discard_flow.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_if_to_cond_assign.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_instructions.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_jumps.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_mat_op_to_vec.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_named_interface_blocks.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_noise.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_output_reads.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_packed_varyings.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_packing_builtins.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_ubo_reference.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_variable_index_to_cond_assign.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_vec_index_to_cond_assign.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_vec_index_to_swizzle.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_vector.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_vector_insert.cpp
SOURCES+=glsl-optimizer/src/glsl/lower_vertex_id.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_algebraic.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_array_splitting.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_constant_folding.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_constant_propagation.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_constant_variable.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_copy_propagation.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_copy_propagation_elements.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_cse.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_dead_builtin_variables.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_dead_builtin_varyings.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_dead_code.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_dead_code_local.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_dead_functions.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_flatten_nested_if_blocks.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_flip_matrices.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_function_inlining.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_if_simplification.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_minmax.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_noop_swizzle.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_rebalance_tree.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_redundant_jumps.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_structure_splitting.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_swizzle_swizzle.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_tree_grafting.cpp
SOURCES+=glsl-optimizer/src/glsl/opt_vectorize.cpp
SOURCES+=glsl-optimizer/src/glsl/s_expression.cpp
SOURCES+=glsl-optimizer/src/glsl/standalone_scaffolding.cpp
SOURCES+=glsl-optimizer/src/glsl/strtod.c
SOURCES+=glsl-optimizer/src/mesa/main/imports.c
SOURCES+=glsl-optimizer/src/mesa/program/prog_hash_table.c
SOURCES+=glsl-optimizer/src/mesa/program/symbol_table.c
SOURCES+=glsl-optimizer/src/util/ralloc.c
SOURCES+=glsl-optimizer/src/util/hash_table.c
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/glslCommon.cpp
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/glslFunction.cpp
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/glslOutput.cpp
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/glslStruct.cpp
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/glslSymbol.cpp
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/hlslCrossCompiler.cpp
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/hlslLinker.cpp
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/hlslSupportLib.cpp
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/propagateMutable.cpp
SOURCES+=hlsl2glslfork/hlslang/GLSLCodeGen/typeSamplers.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/ConstantFolding.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/Gen_hlslang.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/Gen_hlslang_tab.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/HLSL2GLSL.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/InfoSink.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/Initialize.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/IntermTraverse.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/Intermediate.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/ParseHelper.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/PoolAlloc.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/RemoveTree.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/SymbolTable.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/intermOut.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/preprocessor/mojoshader.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/preprocessor/mojoshader_common.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/preprocessor/mojoshader_lexer.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/preprocessor/mojoshader_preprocessor.cpp
SOURCES+=hlsl2glslfork/hlslang/MachineIndependent/preprocessor/sourceloc.cpp
SOURCES+=hlsl2glslfork/hlslang/OSDependent/Mac/ossource.cpp
SOURCES+=md5/md5.c
SOURCES+=mojoshader/mojoshader.c
SOURCES+=mojoshader/mojoshader_common.c
SOURCES+=mojoshader/mojoshader_lexer.c
SOURCES+=mojoshader/mojoshader_preprocessor.c
SOURCES+=main.cpp

OBJECTS=$(SOURCES:%=obj/%.o)

EXECUTABLE=ShaderCompiler

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	gcc $(OBJECTS) -lstdc++ -o $@

obj/%.o: %
	mkdir -p $(dir $@)
	gcc $(CFLAGS) $< -o $@

hlsl2glslfork/hlslang/MachineIndependent/Gen_hlslang.cpp: hlsl2glslfork/hlslang/MachineIndependent/hlslang.l hlsl2glslfork/hlslang/MachineIndependent/Gen_hlslang_tab.cpp
	cd $(dir $@); flex hlslang.l

hlsl2glslfork/hlslang/MachineIndependent/Gen_hlslang_tab.cpp: hlsl2glslfork/hlslang/MachineIndependent/hlslang.y
	cd $(dir $@); bison -o Gen_hlslang_tab.cpp -d -t -v hlslang.y; mv Gen_hlslang_tab.hpp hlslang_tab.h

clean:
	rm -rf obj
	rm -f hlsl2glslfork/hlslang/MachineIndependent/Gen_hlslang.cpp
	rm -f hlsl2glslfork/hlslang/MachineIndependent/Gen_hlslang_tab.cpp

.PHONY: all clean
