//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roblox.Grid.Client
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Status", Namespace = "http://roblox.com/")]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string versionField;

        private int environmentCountField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public int environmentCount
        {
            get
            {
                return this.environmentCountField;
            }
            set
            {
                this.environmentCountField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://roblox.com/", ConfigurationName = "Roblox.Grid.Client.RccService")]
    public interface RccService
    {

        // CODEGEN: Generating message contract since element name GetStatusResult from namespace http://roblox.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://roblox.com/GetStatus", ReplyAction = "http://roblox.com/GetStatusResponse")]
        Roblox.Grid.Client.GetStatusResponse GetStatus(Roblox.Grid.Client.GetStatusRequest request);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://roblox.com/GetStatus", ReplyAction = "http://roblox.com/GetStatusResponse")]
        System.IAsyncResult BeginGetStatus(Roblox.Grid.Client.GetStatusRequest request, System.AsyncCallback callback, object asyncState);

        Roblox.Grid.Client.GetStatusResponse EndGetStatus(System.IAsyncResult result);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetStatusRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetStatus", Namespace = "http://roblox.com/", Order = 0)]
        public Roblox.Grid.Client.GetStatusRequestBody Body;

        public GetStatusRequest()
        {
        }

        public GetStatusRequest(Roblox.Grid.Client.GetStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStatusRequestBody
    {

        public GetStatusRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetStatusResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetStatusResponse", Namespace = "http://roblox.com/", Order = 0)]
        public Roblox.Grid.Client.GetStatusResponseBody Body;

        public GetStatusResponse()
        {
        }

        public GetStatusResponse(Roblox.Grid.Client.GetStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://roblox.com/")]
    public partial class GetStatusResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public Roblox.Grid.Client.Status GetStatusResult;

        public GetStatusResponseBody()
        {
        }

        public GetStatusResponseBody(Roblox.Grid.Client.Status GetStatusResult)
        {
            this.GetStatusResult = GetStatusResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RccServiceChannel : Roblox.Grid.Client.RccService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public Roblox.Grid.Client.Status Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((Roblox.Grid.Client.Status)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RccServiceClient : System.ServiceModel.ClientBase<Roblox.Grid.Client.RccService>, Roblox.Grid.Client.RccService
    {

        private BeginOperationDelegate onBeginGetStatusDelegate;

        private EndOperationDelegate onEndGetStatusDelegate;

        private System.Threading.SendOrPostCallback onGetStatusCompletedDelegate;

        public RccServiceClient()
        {
        }

        public RccServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public RccServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public RccServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public RccServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public event System.EventHandler<GetStatusCompletedEventArgs> GetStatusCompleted;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Roblox.Grid.Client.GetStatusResponse Roblox.Grid.Client.RccService.GetStatus(Roblox.Grid.Client.GetStatusRequest request)
        {
            return base.Channel.GetStatus(request);
        }

        public Roblox.Grid.Client.Status GetStatus()
        {
            Roblox.Grid.Client.GetStatusRequest inValue = new Roblox.Grid.Client.GetStatusRequest();
            inValue.Body = new Roblox.Grid.Client.GetStatusRequestBody();
            Roblox.Grid.Client.GetStatusResponse retVal = ((Roblox.Grid.Client.RccService)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Roblox.Grid.Client.RccService.BeginGetStatus(Roblox.Grid.Client.GetStatusRequest request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetStatus(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetStatus(System.AsyncCallback callback, object asyncState)
        {
            Roblox.Grid.Client.GetStatusRequest inValue = new Roblox.Grid.Client.GetStatusRequest();
            inValue.Body = new Roblox.Grid.Client.GetStatusRequestBody();
            return ((Roblox.Grid.Client.RccService)(this)).BeginGetStatus(inValue, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Roblox.Grid.Client.GetStatusResponse Roblox.Grid.Client.RccService.EndGetStatus(System.IAsyncResult result)
        {
            return base.Channel.EndGetStatus(result);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Roblox.Grid.Client.Status EndGetStatus(System.IAsyncResult result)
        {
            Roblox.Grid.Client.GetStatusResponse retVal = ((Roblox.Grid.Client.RccService)(this)).EndGetStatus(result);
            return retVal.Body.GetStatusResult;
        }

        private System.IAsyncResult OnBeginGetStatus(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginGetStatus(callback, asyncState);
        }

        private object[] OnEndGetStatus(System.IAsyncResult result)
        {
            Roblox.Grid.Client.Status retVal = this.EndGetStatus(result);
            return new object[] {
                    retVal};
        }

        private void OnGetStatusCompleted(object state)
        {
            if ((this.GetStatusCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStatusCompleted(this, new GetStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetStatusAsync()
        {
            this.GetStatusAsync(null);
        }

        public void GetStatusAsync(object userState)
        {
            if ((this.onBeginGetStatusDelegate == null))
            {
                this.onBeginGetStatusDelegate = new BeginOperationDelegate(this.OnBeginGetStatus);
            }
            if ((this.onEndGetStatusDelegate == null))
            {
                this.onEndGetStatusDelegate = new EndOperationDelegate(this.OnEndGetStatus);
            }
            if ((this.onGetStatusCompletedDelegate == null))
            {
                this.onGetStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStatusCompleted);
            }
            base.InvokeAsync(this.onBeginGetStatusDelegate, null, this.onEndGetStatusDelegate, this.onGetStatusCompletedDelegate, userState);
        }
    }
}
