set(CURL_AVAILABLE OFF)

if (ANDROID)
  # Probe multiple contrib locations for cURL depending on ABI naming
  set(_curl_candidates)
  if (DEFINED ANDROID_ABI)
    list(APPEND _curl_candidates "${CONTRIB_PATH}/android/${ANDROID_ABI}/curl/curl-7.43.0")
  endif()
  # Also try canonical 'arm' and common legacy names
  list(APPEND _curl_candidates
    "${CONTRIB_PATH}/android/arm/curl/curl-7.43.0"
    "${CONTRIB_PATH}/android/armeabi-v7a/curl/curl-7.43.0"
    "${CONTRIB_PATH}/android/armeabi-v7a with NEON/curl/curl-7.43.0"
  )

  set(CURL_ROOT "")
  foreach(_cand IN LISTS _curl_candidates)
    file(TO_CMAKE_PATH "${_cand}" _cand_norm)
    if (EXISTS "${_cand_norm}/include/curl/curl.h")
      set(CURL_ROOT "${_cand_norm}")
      break()
    endif()
  endforeach()

  if (CURL_ROOT)
    include_directories("${CURL_ROOT}/include")
    if (EXISTS "${CURL_ROOT}/lib")
      link_directories("${CURL_ROOT}/lib")
    endif()
    set(CURL_AVAILABLE ON)
  else()
    # Fallback to the NDK build output location inside the Windows curl tree (legacy setup)
    file(TO_CMAKE_PATH "${CONTRIB_PATH}/windows/x86/curl/curl-7.43.0" CURL_SRC_ROOT)
    set(_curl_src_inc "${CURL_SRC_ROOT}/include")
    # Typical ndk-build output path for static lib (armeabi-v7a)
    set(_curl_ndk_libdir "${CURL_SRC_ROOT}/packages/Android/obj/local/armeabi-v7a")
    set(_curl_ndk_lib "${_curl_ndk_libdir}/libcurl.a")
    if (EXISTS "${_curl_src_inc}/curl/curl.h" AND EXISTS "${_curl_ndk_lib}")
      include_directories("${_curl_src_inc}")
      link_directories("${_curl_ndk_libdir}")
      set(CURL_AVAILABLE ON)
    else()
      message(STATUS "cURL for Android not found. Checked: ${_curl_candidates}. If you are building for ${ANDROID_ABI}, run: tools/build-curl-android.cmd ${ANDROID_ABI} 16 Release")
    endif()
  endif()
else()
  # Non-Android platforms use Windows contrib path in this tree
  file(TO_CMAKE_PATH "${CONTRIB_PATH}/windows/x86/curl/curl-7.43.0" CURL_ROOT)
  if (EXISTS "${CURL_ROOT}/include")
    include_directories("${CURL_ROOT}/include")
  endif()
  if (EXISTS "${CURL_ROOT}/lib")
    link_directories("${CURL_ROOT}/lib")
  endif()
  set(CURL_AVAILABLE ON)
endif()
